### ISSUE TITLE
ASE in `pyproject.toml`

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [orbital-materials/orb-models#3]
First of all, huge congratulations on the release!!! Very exciting!

A minor comment: you have `ase` listed twice in `pyproject.toml`: https://github.com/orbital-materials/orb-models/blob/0438173f5b426c0e2eafa8ace06bd06ab4746247/pyproject.toml#L19-L25.

Also, I see you have pinned ASE to 3.22.1. If you need help transitioning to 3.23.0, just let me know!

**Comment by AntObi** [comment]
The ASE requirement can be loosened to `ase>=3.22.1` rather than the strict pinning. Using ASE 3.23.0 doesn't break any of the tests, so upgrading to ASE 3.23.0 should be very straightforward!

**Comment by benrhodes26** [comment]
Thanks guys; I'll include both changes in a PR I just opened to clean various things up :)

**Comment by Andrew-S-Rosen** [comment]
Wonderful, this will help me out a lot!
