### ISSUE TITLE
Reading latest checkpoint during fine-tuning

### ISSUE THREAD

**Issue by R1j1t** [orbital-materials/orb-models#32]
Firstly great package! It is easy to use and hopefully the fine tuning gives me expected results. 

In this regard, I think there is a little room for improvement where we can read the latest checkpoint instead of fine tuning from scratch for every run. I have made this changes for my local and I am happy to open a PR for feedback.

Below are some high level changes:
```py
def get_latest_checkpoint(ckpt_folder):
    # Define the regex pattern for the checkpoint filenames
    pattern = re.compile(r'^checkpoint_epoch(\d+)\.ckpt$')
    max_epoch = -1
    for filename in os.listdir(ckpt_folder):
        file_path = os.path.join(ckpt_folder, filename)
        
        if os.path.isfile(file_path):
            match = pattern.match(filename)
            if match:
                epoch = int(match.group(1))
                if epoch > max_epoch:
                    max_epoch = epoch
    return max_epoch


def run(args):
....
    ckpt_epoch=get_latest_checkpoint(ckpt_folder)

    # Instantiate model
    if ckpt_epoch>-1:
        model = pretrained.orb_d3_v2(device=device, weights_path=f'.../ckpts/checkpoint_epoch{ckpt_epoch}.ckpt')
    else:
        model = pretrained.orb_d3_v2(device=device)
....
```

**Comment by DeNeutoy** [comment]
Thanks! The finetuning script is meant to be for exemplary purposes only, so the fact you've modified it locally to suit your needs is actually the intended use. Glad it's working nicely for you!
