### ISSUE TITLE
add more details about the orb_v2 models

### ISSUE THREAD

**Issue by zdcao121** [orbital-materials/orb-models#33]
Can you provide more training details about the `orb_v2` model? I'm curious about how you integrate the `MPTraj` and `Alex` datasets. Additionally, can we assume that the energy predicted by the model is based on the mixture of GGA and GGA+U  functionals ?

**Comment by benrhodes26** [comment]
We have submitted a technical report to Arxiv; it should be available within the next 24 hours :)

Yes, you are correct that, because our version of MPTrj contains uncorrected entries, the model is predicting a mixture of GGA and GGA+U.

We will hopefully address this in future versions.

**Comment by zdcao121** [comment]
Thanks for your reply!
