### ISSUE TITLE
Widom Insertion Method Example

### ISSUE THREAD

**Issue by cfarm6** [orbital-materials/orb-models#34]
Hello,

In reading your paper, you mention performing studies on the adsorption of CO2 in Mg-MOF-74. Can you provide an example for performing a simple Widom particle insertion study? 

Thank you,
Carson

**Comment by benrhodes26** [comment]
Unfortunately the Widom insertion logic is embedded in our proprietary code and we don't have the bandwidth to refactor and release it.

Apologies we couldn't be of more assistance!
