### ISSUE TITLE
Pynanoflann in `pyproject.toml`

### ISSUE THREAD

**Issue by AntObi** [orbital-materials/orb-models#5]
Congratulations on this exciting release!

https://github.com/orbital-materials/orb-models/blob/0438173f5b426c0e2eafa8ace06bd06ab4746247/pyproject.toml#L18-L26

`pynanoflanno` can be included in the pyproject.toml file in the dependencies as follows:

```toml
 dependencies = [ 
     "cached_path>=1.6.2", 
     "ase>=3.22.1", 
     "numpy<2.0.0", 
     "scipy>=1.13.1", 
     "torch==2.2.0", 
     "pynanoflann@git+https://github.com/dwastberg/pynanoflann#egg=af434039ae14bedcbb838a7808924d6689274168", 
     "dm-tree>=0.1.8", 
 ] 
```

I've verified that an installation like this works on my local machine, which can make downloads easier for new users to the package, as well as making the PyPI installation of `orb` simpler.

**Comment by utf** [comment]
Hi @AntObi, you can add github links in pyproject but unfortunately you can't then upload it to Pypi. So this works for local installation but not with `pip install orb-models`.
